In [1]:
print("Hey Ppl! Welcome to New Gen Learning!")

Hey Ppl! Welcome to New Gen Learning!


In [3]:
print('Hey, Check this out!')

Hey, Check this out!


In [5]:
print("https://jupyter.org/install")
#This is the jupyther notebook URL

https://jupyter.org/install


In [6]:
x=5
print(x)

5


In [7]:
y="XMen"
print(y)

XMen


In [12]:
x,y,z="John", "Zac", "Den" 
print(z)

Den


In [13]:
x = "awesome"

def myfunc():
  print("Python is " + x)

myfunc()

Python is awesome


In [15]:
#Python has the following data types built-in by default, in these categories:
"""
Text Type:	str
Numeric Types:	int, float, complex
Sequence Types:	list, tuple, range
Mapping Type:	dict
Set Types:	set, frozenset
Boolean Type:	bool
Binary Types:	bytes, bytearray, memoryview
None Type:	NoneType
"""

'\nText Type:\tstr\nNumeric Types:\tint, float, complex\nSequence Types:\tlist, tuple, range\nMapping Type:\tdict\nSet Types:\tset, frozenset\nBoolean Type:\tbool\nBinary Types:\tbytes, bytearray, memoryview\nNone Type:\tNoneType\n'

In [5]:
x=2.5 #float

y= 1j #complex
print(type(y))

z="Denila"
print(type(z))


<class 'complex'>
<class 'str'>


In [9]:
#Sequence
x=["Avengers", "Marvels","Deadpool", "Wolverine"] #list
y=("apple", "mango","mango") #tuple
z=range(5)
print(y)
print(z)

('apple', 'mango', 'mango')
range(0, 5)


In [11]:
#mapping
q={"name":"Denila", "age": 51, "gender":"Female"}
print(q)

{'name': 'Denila', 'age': 51, 'gender': 'Female'}


In [13]:
w={"cherry", "grapes","cherry"}#set
print(w)

{'grapes', 'cherry'}


In [23]:
x=True
y=False
#boolean

In [14]:
x=b"Hello" #bytes
print(x)
y=bytearray(5) #bytearray
print(y)
z=memoryview(bytes(5))
print(z)

b'Hello'
bytearray(b'\x00\x00\x00\x00\x00')


In [30]:
x=None

In [ ]:
#Python Operators
Arithmetic operators
Assignment operators
Comparison operators
Logical operators
Identity operators
Membership operators
Bitwise operators

In [16]:
#Arithmetic Ops:
#+, -, *, /, %, **, //
x=4
y=5
print(x+y)

print(x%y)
print(x**y)
print(x//y)

9
4
1024
0


In [35]:
#Assignment ops:
# = , +=, -=,  (=arithmetic ops)
x=5
x -=3
print(x)


2


In [36]:
#&=

x=5
x&=3
print(x)

1


In [37]:
x=5
x|=3
print(x)

7


In [38]:
print(x:=3)

3


In [39]:
#Comparison operators
#==, !=, >,<,<=, >=
a=4
b=6
print(a>=b)

False


In [40]:
#Logical 
# and , or , not
#and Returns True if both statements are true

a=3
print(a>2 and a<5)

True


In [41]:
#or : Returns True if one of the statements is true

In [42]:
# NOT
a=3
print(not(a>2 and a<5))

False


In [18]:
# Identity Ops:
#is: Returns True if both variables are the same object, 
#is not

x=["apple","cherry"]
y=["apple","cherry"]
z=x

print(x is z)


True


In [45]:
#is not: Returns True if both variables are not the same object

In [47]:
# Membership ops:
#in: Returns True if a sequence with the specified value is present in the object
#not in: Returns True if a sequence with the specified value is not present in the object

x=["apple","cherry"]
print("cherry" in x)
print("mango" in x)

True
False


In [48]:
#Bitwise Ops:
# &, |, ^, ~, <<, >>

print(3<<2)

12


In [49]:
# Python List
x=["apple","cherry", "mango"]
# List are ordered, changeable and allows duplicates

print(x[-1])

mango


In [50]:
x=["apple","cherry", "mango"]
x[1]="banana"
print(x)

['apple', 'banana', 'mango']


In [51]:
x=["apple","cherry", "mango"]
#append
#remove
#pop()
#del
del x
#clear

In [52]:
#Loop list
x=["apple","cherry", "mango"]
for y in x:
    print(y)

apple
cherry
mango


In [55]:
#Sort the list alphabetically:
x=["apple","watermelon","cherry", "mango"]
x.sort()
print(x)


['apple', 'cherry', 'mango', 'watermelon']


In [56]:
x=["apple","watermelon","cherry", "mango"]
x.sort(reverse=True) #reverse the list aplhabetically
print(x)

['watermelon', 'mango', 'cherry', 'apple']


In [57]:
x=["apple","watermelon","cherry", "mango"]
a= x.copy() 
print(a)

['apple', 'watermelon', 'cherry', 'mango']


In [58]:
#list method
x=["apple","watermelon","cherry", "mango"]
a=list(x)
print(a)

['apple', 'watermelon', 'cherry', 'mango']


In [59]:
#join list
x=["apple","watermelon","cherry", "mango"]
a= [1,2,3]
y=x+a
print(y)

['apple', 'watermelon', 'cherry', 'mango', 1, 2, 3]


In [60]:
#extend method
x=["apple","watermelon","cherry", "mango"]
a= [1,2,3]
x.extend(a)
print(x)

['apple', 'watermelon', 'cherry', 'mango', 1, 2, 3]


In [65]:
z= ['apple', 'watermelon', 'cherry', 'mango', 1, 2, 3]
#exercise: Print the second item in the list
#Remove cherry from the list and print the new list
#Also add this list to the existing one: a=[123,234,345]
#reverse the list


In [66]:
#python tuples:
# Tuples are ordered, unchangeable, allows duplicate values

In [67]:
x=("apple","watermelon","cherry", "mango")
y= list(x)
print(y)

['apple', 'watermelon', 'cherry', 'mango']


In [68]:
a=['apple', 'watermelon', 'cherry', 'mango']
b= tuple(a)
print(b)

('apple', 'watermelon', 'cherry', 'mango')


In [71]:
#Unpacking a tuple
x=("apple","watermelon","cherry", "mango")
(green, yellow, orange, red) =x
print(green)
print(red)

apple
mango


In [72]:
x=("apple","watermelon","cherry", "mango", "grapes")
(green, yellow, *red) = x
print(red)

['cherry', 'mango', 'grapes']


In [73]:
#Loop the tuple
x=("apple","watermelon","cherry", "mango", "grapes")
for y in x:
    print(y)

apple
watermelon
cherry
mango
grapes


In [74]:
#join tuple
x=("apple","watermelon","cherry", "mango", "grapes")
y=(912,23,34,45)
a=x+y
print(a)

('apple', 'watermelon', 'cherry', 'mango', 'grapes', 912, 23, 34, 45)


In [75]:
#multiply the tuples
x=("apple","watermelon","cherry", "mango", "grapes")
m= x*2
print(m)

('apple', 'watermelon', 'cherry', 'mango', 'grapes', 'apple', 'watermelon', 'cherry', 'mango', 'grapes')


In [76]:
#Tuple methods:
#count(): Returns the number of times a specified value occurs in a tuple
#index(): Searches the tuple for a specified value and returns the position of where it was found

In [ ]:
#tuple ex:
x=("apple","watermelon","cherry", "mango", "grapes")
y=(912,23,34,45)
#Add both the tuples
#Count the values in the tuple
#Specify the last value from the tuple


In [78]:
#Python Functions: A function is a block of code which only runs when it is called.
def my_func():
    print("Hey!Let's get started")

my_func()

Hey!Let's get started


In [79]:
#Arguments:
#Information can be passed into functions as arguments
def my_func(fname):
    print( fname + "Hey!Let's get started")

my_func("Ben")

BenHey!Let's get started


In [81]:
def my_func(fname,lname):
    print( fname + lname + "Hey!Let's get started")

my_func("Ben ", "Warner ")

Ben Warner Hey!Let's get started


In [82]:
def my_func(f,l):
    print( f + l + "Hey!Let's get started")

my_func("1 ", "2 ")

1 2 Hey!Let's get started


In [84]:
def func(*ppl):
    print("The smart ones are working " + ppl[2])

func("smart", "lazy", "hard")
          

The smart ones are working hard


In [ ]:
#Key=value syntax
#kwargs

In [88]:
def func(ppl1, ppl2, ppl3):
    print("The smart ones are working " + ppl1 +ppl2)

func("smart", "lazy", "hard")
          
          

The smart ones are working smartlazy


In [90]:
def func(x):
    return 6*x
print(func(4))
print(func(5))
#return a value


24
30


In [92]:
def func(x):
    pass

#pass statement
    


In [93]:
#Lambda: small anoymous function
#Lambda function can take any number of arguments, but can only have one expression.
#lambda arguments: expression (syntax)


In [94]:
x=lambda a: a-5
print(x(10))

5


In [97]:
x=lambda a,b,c: a-b-c
print(x(10,4,5))

1


In [98]:
#Lambda with function
def func(a):
    return lambda x :x*a

mydoubler=func(2)

print(mydoubler(4))

8


In [99]:
# exercise:
# Q1: passing multiple arguments inside a function
#Q2: lambda with 3 arguments
#Q3: lambda inside a function

In [100]:
#Arrays: Arrays are used to store multiple values in one single variable

In [101]:
cars=["Ford", "BMW", "Tata"]
print(cars)

['Ford', 'BMW', 'Tata']


In [102]:
cars=["Ford", "BMW", "Tata"]
print(cars[0])

Ford


In [104]:
cars=["Ford", "BMW", "Tata"]
x=len(cars)
print(x)

3


In [105]:
cars=["Ford", "BMW", "Tata"]
for x in cars:
    print(x)

Ford
BMW
Tata


In [106]:
cars=["Ford", "BMW", "Tata"]
cars.append("Maruti")
print(cars)

['Ford', 'BMW', 'Tata', 'Maruti']


In [107]:
#exercise
#sort
#reverse


In [111]:
#python classes and objects: Create a class named MyClass, with a property named x
class MyClass:
    x=3
p=MyClass()

print(p.x)

3


In [115]:
class Person:
    def __init__(self,name,age):
        self.name= name
        self.age= age
        
p1=Person("Ben", 20)

print(p1.name)
print(p1.age)

Ben
20


In [116]:
#insert another function by using print, greet Ben (exercise)


In [117]:
#self parameter
""""The self parameter is a reference to the current instance of the class, and is used to access variables that belongs to the class.

It does not have to be named self , you can call it whatever you like, but it has to be the first parameter of any function in the class:"""

Example
class Person:
    def __init__(app,name,age):
        app.name= name
        app.age= age
        
p1=Person("Ben", 20)

print(p1.name)
print(p1.age)

Ben
20


In [118]:
class Person:
    def __init__(app,name,age):
        app.name= name
        app.age= age
        
p1=Person("Ben", 20)

p1.age=40 # modify object

print(p1.name)
print(p1.age)

Ben
40


In [121]:
class Person:
    def __init__(app,name,age):
        app.name= name
        app.age= age
        
p1=Person("Ben", 20)

del p1.age

print(p1.name)
print(p1.age)

Ben


AttributeError: 'Person' object has no attribute 'age'

In [122]:
class Person:
    pass

#pass statement in class

In [123]:
#Python Datetime

import datetime
x=datetime.datetime.now()
print(x)

2024-07-25 12:06:28.266021


In [126]:
import datetime
x=datetime.datetime.now()
print(x.year)
print(x.strftime("%A"))

2024
Thursday


In [127]:
#display another date
import datetime
x=datetime.datetime(2020,1, 18)
print(x)

2020-01-18 00:00:00


In [128]:
#display another date
import datetime
x=datetime.datetime(2020,1, 18)
print(x.strftime("%B"))

January


In [129]:
#exercise:
#display the current date and time
#display the year 2023 and any month in your date

In [130]:
#python Math
x= min(12,20,9)
y=max(12,20,9)

print(x)
print(y)

9
20


In [132]:
x= abs(-9)
print(x)

9


In [133]:
x= abs(45) # absolute positive
print(x)

45


In [134]:
x= pow(2,3) #exponential
print(x)

8


In [135]:
#math Module
import math
q=math.sqrt(64)
print(q)

8.0


In [136]:
import math
x=math.pi
print(x)

3.141592653589793


In [137]:
# ex:
"""
1: Display the sqrt of 125
2. Try min and max
"""


'\n1: Display the sqrt of 125\n2. Try min and max\n'

In [138]:
#python JSON
"""JSON is a syntax for storing and exchanging data.

JSON is text, written with JavaScript object notation."""

'JSON is a syntax for storing and exchanging data.\n\nJSON is text, written with JavaScript object notation.'

In [142]:
#convert python to json
import json
x={
    "name":"Ben",
    "age": 65,
    "city": "London"
}

y=json.dumps(x)

print(y)

{"name": "Ben", "age": 65, "city": "London"}


In [141]:
import json
x='{"name":"Ben", "age": 34, "city": "NY"}'
y=json.loads(x)
print(y["age"])

34


In [143]:
import json
print(json.dumps(("abc", "vcd")))

["abc", "vcd"]


In [144]:
'''dict
list
tuple
string
int
float
True
False
None'''
# py objs to json strings

'dict\nlist\ntuple\nstring\nint\nfloat\nTrue\nFalse\nNone'

In [146]:
#convert python dict and list to json strings- exercise

In [150]:
import json
x={
    "name":"Ben",
    "age": 65,
    "city": "London"
}


print(json.dumps(x, indent=4, sort_keys=True,separators=(".", "=")))

{
    "age"=65.
    "city"="London".
    "name"="Ben"
}


In [151]:
#convert python dict and list to json strings.add indent=6,  sort and separate

In [155]:
#python RegEx: A RegEx, or Regular Expression, is a sequence of characters that forms a search pattern.
#RegEx can be used to check if a string contains the specified search pattern.
import re
txt="It is raining today"
x=re.search("^It.*today$",txt)

if x:
    print("It is a match")
else:
    print("No match")

It is a match


In [2]:
import re
txt="It is raining today, is it?"
x=re.findall("it",txt)
print(x)

['it']


In [158]:
#Try search and Findall - Exercise


In [165]:
import re
txt="It is raining today, is it?"
x=re.split("\s",txt)
print(x)

['It', 'is', 'raining', 'today,', 'is', 'it?']


<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
C:\Users\DenilaRajendran\AppData\Local\Temp\ipykernel_3792\3019338207.py:3: SyntaxWarning: invalid escape sequence '\s'
  x=re.split("\s",txt)


In [3]:
import re
txt="It is raining today, is it?"
x=re.sub("\s","&",txt)
print(x)

It&is&raining&today,&is&it?


<>:3: SyntaxWarning: invalid escape sequence '\s'
<>:3: SyntaxWarning: invalid escape sequence '\s'
C:\Users\DenilaRajendran\AppData\Local\Temp\ipykernel_248\4279226124.py:3: SyntaxWarning: invalid escape sequence '\s'
  x=re.sub("\s","&",txt)


In [168]:
# re: Split, sub, findall and search

In [1]:
#Numpy: Numerical Python. It is  a Python Library

In [2]:
#The array object in NumPy is called ndarray

In [3]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [4]:
import numpy as np #alias

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
#checking numpy version
import numpy as np
print(np.__version__)

1.26.4


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
"""Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).
Nesterd arrays: are arrays that have arrays as their elements."""

In [9]:
#0D
import numpy as np
a=np.array(42)
print(a)

42


In [10]:
#1D
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [12]:
#2D
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [3, 4, 5, 6, 7]])

print(arr)

[[1 2 3 4 5]
 [3 4 5 6 7]]


In [13]:
#exercise : execute a 3D array

In [14]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [3, 4, 5, 6, 7]])

print(arr)
print(arr.ndim)

[[1 2 3 4 5]
 [3 4 5 6 7]]
2


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4],ndmin=5)

print(arr)
print('No. of dim:' , arr.ndim)


[[[[[1 2 3 4]]]]]
No. of dim: 5


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [23]:
#exercise: create an for 6 dimensional, print the array and the no. of dimensions

In [24]:
#1D
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[1])

2


In [25]:
#1D
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr[1]+ arr[3])

6


In [28]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [3, 4, 5, 6, 7]])

print(arr[0,1])
print(arr[1,4])

2
7


In [29]:
# exercise: Fetch the 4th value from the 3rd array in a 4D array

In [30]:
"""Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1"""

"Slicing arrays\nSlicing in python means taking elements from one given index to another given index.\n\nWe pass slice instead of index like this: [start:end].\n\nWe can also define the step, like this: [start:end:step].\n\nIf we don't pass start its considered 0\n\nIf we don't pass end its considered length of array in that dimension\n\nIf we don't pass step its considered 1"

In [31]:
#Slicing Arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4,6, 7,8])

print(arr[1:4])

[2 3 4]


In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4,6, 7,8])

print(arr[3:7])

[4 5 4 6]


In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4,6, 7,8])

print(arr[3:])

[4 5 4 6 7 8]


In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4,6, 7,8])

print(arr[:4])

[1 2 3 4]


In [41]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4,6, 7,8])

print(arr[1:])

[2 3 4 5 4 6 7 8]


In [43]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [3, 4, 5, 6, 7]])

print(arr[0: 2, 1:4])


[[2 3 4]
 [4 5 6]]
