In [12]:
snake_case=3
print(snake_case)
print(type(snake_case))


3
<class 'int'>


In [10]:
TomBoy=5
print(TomBoy)

5


In [6]:
name = "Bill Teddington"
other_name = "Sally Sussington"

In [8]:
#This is a print command
print("This is Python course")

This is Python course


In [9]:
"""THis
is 
a 
multiple line of comment"""

'THis\nis \na \nmultiple line of comment'

In [11]:
# Exercise:
#Show 3 diff naming conventions along with a  comment

In [15]:
#Exercise: Display each type
"""Text Type:	str
Numeric Types:	int, float, complex
Sequence Types:	list, tuple, range
Mapping Type:	dict"""

'Text Type:\tstr\nNumeric Types:\tint, float, complex\nSequence Types:\tlist, tuple, range\nMapping Type:\tdict'

In [16]:
"""Exercise: Set Types:	set, frozenset
Boolean Type:	bool
Binary Types:	bytes, bytearray, memoryview
None Type:	NoneType
"""
#Exercise: Display each type

'Exercise: Set Types:\tset, frozenset\nBoolean Type:\tbool\nBinary Types:\tbytes, bytearray, memoryview\nNone Type:\tNoneType\n'

In [17]:
"""Exercise: Showcase any 3 arithmetic, assignment and logical ops"""

'Exercise: Showcase any 3 arithmetic, assignment and logical ops'

In [18]:
user_input = input("Enter your name: ")

Enter your name:  Denila


In [19]:
print("Hey! Let's get started")

Hey! Let's get started


In [22]:
print("Hello","world!", sep=":", end ="#")

Hello:world!#

In [23]:
# Ex: Identity, Membership, bitwise (Any 3) , input, print along with end and sep parameter

In [24]:
name="Python"
print(name[0])

P


In [25]:
name="Pythonwererttyt"
print(name[-1])

t


In [26]:
name="Pythonwererttyt"
print(name[0:5])

Pytho


In [29]:
#Exercise:
"""String
string="Today is the Day. Make the most of it!"
rem="Remind youself"
perform slicing, concatenation, f-string,len and upper and lower case"""

'String\nstring="Today is the Day. Make the most of it!"\nrem="Remind youself"\nperform slicing, concatenation, f-string,len and upper and lower case'

In [30]:
# Implicit an dexplicit casting, Handle one error-

In [31]:
x = 42
x_str = str(x) # Explicitly converts integer to string
print("The answer is " + x_str)

The answer is 42


In [36]:
x="Helllo"
n=123
n1=str(n)
print(x + str(n1))
print(n1)
print(x + n1)

Helllo123
123
Helllo123


In [37]:
z= ['apple', 'watermelon', 'cherry', 'mango', 1, 2, 3]
#exercise: Print the second item in the list
#Remove cherry from the list and print the new list
#Also add this list to the existing one: a=[123,234,345]
#reverse the list


In [38]:
#tuple ex:
x=("apple","watermelon","cherry", "mango", "grapes")
y=(912,23,34,45)
#Add both the tuples
#Count the values in the tuple
#Specify the last value from the tuple


In [39]:
#Set and range- range to list and set operations

In [40]:
# Exercise: Dictionaries (Any 3 types)

In [11]:
#Conditional Statements:
age=1
if age>=35:
    print("He is elder")
elif age==1:
    print("He is a toddler")
else:
    print("He is an old man")

He is a toddler


In [6]:
#Execute code for if, if-else, if-elif-else, nested if


In [ ]:
#While condition
"""
n=1
while n<=1:
    n+=2
    print(n)
"""
#Improvise this code and execute using Break and continue


In [16]:
x = [1, 2]
y = [4, 5]
for i in x:
    for j in y:
        print(i, j)

1 4
1 5
2 4
2 5


In [17]:
x = [1, 2, 9]
y = [4, 5, 8]
for i in x:
    for j in y:
        print(i, j)

1 4
1 5
1 8
2 4
2 5
2 8
9 4
9 5
9 8


In [18]:
#Function: Resuable of specific block of code
"""Execute the 4 codes"""

'Execute the 4 codes'

In [19]:
#Lambda function: Annoymous function
#Syntax Lambda argument: Expression


In [23]:
q=[("John", 20),("Ben",24),("Adam",36)]
q.sort(key=lambda x:x[1])
print(q)
#1: according to the number

[('John', 20), ('Ben', 24), ('Adam', 36)]


In [21]:
q=[("John", 20),("Ben",24)]
q.sort(key=lambda x:x[0])
print(q)
#o: Alphabetical order

[('Ben', 24), ('John', 20)]


In [22]:
q=[("John", 20),("Ben",24)]
q.sort(key=lambda x:x[2])
print(q)

IndexError: tuple index out of range

In [24]:
q=[("John", 20),("Ben",24),("Adam",36)]
q.sort(key=lambda x:x[0])
print(q)

[('Adam', 36), ('Ben', 24), ('John', 20)]


In [27]:
#Python class and object
#Display the difference in both class attribute and instance attribute 

In [28]:
#Inheritance and polymorphism- Execution of code

In [33]:
#Encapsulation
"""Create a multi-level class where 3 objects wil be created and the third object will be called referencing the second class"""


'Create a multi-level class where 3 objects wil be created and the third object will be called referencing the second class'

In [34]:
numbers = [1, 2, 3, 4, 5]
for num in numbers:
 print(num)

1
2
3
4
5


In [39]:
numbers = [1, 2, 3, 4, 5]
iter_numbers = iter(numbers)

print(next(iter_numbers)) # Output: 1
print(next(iter_numbers)) # Output: 2
print(next(iter_numbers))
print(next(iter_numbers))
print(next(iter_numbers))


1
2
3
4
5


In [41]:
def square_numbers(nums):
    for num in nums:
        yield num * num
numbers = [1, 2, 3, 4, 5]
squares = square_numbers(numbers)
for square in squares:
 print(square)


1
4
9
16
25


In [42]:
# Exercise:
# Execute the code for Iterators and Scope(All 4)

In [43]:
import logging
name = 'GFG'
logging.error('%s raised an error', name)


ERROR:root:GFG raised an error


In [44]:
# importing module
import logging

# Create and configure logger
logging.basicConfig(filename="newfile.log",
					format='%(asctime)s %(message)s',
					filemode='w')

# Creating an object
logger = logging.getLogger()

# Setting the threshold of logger to DEBUG
logger.setLevel(logging.DEBUG)

# Test messages
logger.debug("Harmless debug Message")
logger.info("Just an information")
logger.warning("Its a Warning")
logger.error("Did you try to divide by zero")
logger.critical("Internet is down")


DEBUG:root:Harmless debug Message
INFO:root:Just an information
ERROR:root:Did you try to divide by zero
CRITICAL:root:Internet is down


In [46]:
import re
#Check if the string starts with "The" and ends with "Spain":

txt = "The rain in Spain"
x = re.search("^The.*Spain$", txt)

if x:
  print("YES! We have a match!")
else:
  print("No match")


YES! We have a match!


In [47]:
import camelcase

c = camelcase.CamelCase()

txt = "lorem ipsum dolor sit amet"

print(c.hump(txt))

#This method capitalizes the first letter of each word.


Lorem Ipsum Dolor Sit Amet


In [49]:
#Numpy
import numpy as np
k=np.array([[1,2,3],[2,4,5],[6,7,8]])
print(k)
print(k.shape)

[[1 2 3]
 [2 4 5]
 [6 7 8]]
(3, 3)


In [50]:
#Execute for 4*3 dimension


In [52]:
#Execute np.arange(15) and dispaly the last fourth value

In [53]:
#Execute x.shape(3,6) and show the 3rd value from the 2nd row

In [55]:
a=np.ones((1,2,3))
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [57]:
a=np.ones((2,2,3))
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [58]:
a=np.ones((3,2,3))
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
