<div class="alert alert-block alert-success" style="margin-top: 20px">
 <h1>Matrix Operations using TensorFlow</h1>
</div>

In [1]:
# Created by: ADMINIXTRATOR             Date: 12th January, 2020
# Twitter: Adminixtrator                Email: minixtrator@gmail.com
# 
# Python version: 3.7.4 amd64 (64-bit)    TensorFlow: 2.0.0

import tensorflow as tf

tf2x = tf.compat.v1
tf2x.InteractiveSession()

In [2]:
# TensorFlow provides shortcuts to creating the most commonly used matrices
# We will be starting with the identity matrix which is created with 'tf.eye()'

tf.eye(5).numpy()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [3]:
# Diagonal matrices are another form of commonly used matrices
# The easiest way is to use the range attribute, then the diagonal matrix is constructed from the 
# resulting vector

a = tf.range(2, 10, 2).numpy()
tf2x.diag(a).numpy()

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]], dtype=int32)

In [4]:
# So let's see what the vector 'a' looks like...
# The range attribute is used as 'tf.range(start, end, delta)'

a

array([2, 4, 6, 8], dtype=int32)

In [5]:
# To find the determinant of a matrix, the 'tf.matrix_determinant()' attribute is used
# It accepts a matrix as an input, say for example the identity matrix

a = tf.eye(4).numpy()
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [6]:
tf2x.matrix_determinant(a).numpy()

1.0

In [7]:
# Now to the transpose of a matrix
# To transpose a matrix, the 'tf.matrix_transpose()' attribute is used
# The 'matrix_transpose()' function accepts a matrix as an input, so let us start with a simple matrix

b = tf.eye(3,4).numpy()
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]], dtype=float32)

In [8]:
tf2x.matrix_transpose(b).numpy()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)

In [9]:
# The inverse of a matrix can also be done using the 'tf.matrix_inverse()' attribute
# The 'matrix_inverse()' function accepts only square matrices i.e. matrices having
# the same lenght of rows and columns
# Using the numpy library, let's quickly create a simple matrix

import numpy as np

c = np.matrix(np.arange(0.1,1.9,0.2).reshape(3,3))*10
c

matrix([[ 1.,  3.,  5.],
        [ 7.,  9., 11.],
        [13., 15., 17.]])

In [10]:
tf2x.matrix_inverse(c).numpy()

array([[-2.81474977e+14,  5.62949953e+14, -2.81474977e+14],
       [ 5.62949953e+14, -1.12589991e+15,  5.62949953e+14],
       [-2.81474977e+14,  5.62949953e+14, -2.81474977e+14]])

In [11]:
# The 'tf.matmul()' attribute is also used to multiply matrices
# If you are new to matrix multiplication, it is advised you look it up online or see the repo below

d = tf.eye(3,4).numpy()
e = tf.eye(4,3).numpy()

tf.matmul(d,e).numpy()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

<div class="alert alert-block alert-info" style="margin-top: 20px">
    <img src="markdown/logo.png" alt="Template image">
    <h2><a href="https://github.com/Adminixtrator/Numpy_Matrix_Calculator">Numpy Matrix Calculator</a></h2>
</div>

<div class="alert alert-block alert-warning" style="margin-top: 20px">
 <h3>Type Conversion</h3>
</div>

In [12]:
# If a consistent observation has been made, you should see that the tensors we have been working on,
# have different types. int32, int64, float32 etc.
# Let's breifly look at the TYPE CONVERSION
# To convert a tensor from one type to another, say int32 to float32. The 'tf.to_float32' attribute is used

a = tf.fill((1,5),2).numpy()
a

array([[2, 2, 2, 2, 2]], dtype=int32)

In [13]:
tf2x.to_float(a).numpy()

Instructions for updating:
Use `tf.cast` instead.


array([[2., 2., 2., 2., 2.]], dtype=float32)

In [14]:
tf2x.to_int64(a)

Instructions for updating:
Use `tf.cast` instead.


<tf.Tensor: id=52, shape=(1, 5), dtype=int64, numpy=array([[2, 2, 2, 2, 2]])>

In [15]:
tf.cast(a, dtype=tf.float64)

<tf.Tensor: id=54, shape=(1, 5), dtype=float64, numpy=array([[2., 2., 2., 2., 2.]])>

In [16]:
tf2x.to_double(a)

Instructions for updating:
Use `tf.cast` instead.


<tf.Tensor: id=56, shape=(1, 5), dtype=float64, numpy=array([[2., 2., 2., 2., 2.]])>

In [17]:
a = tf.ones((3,4), dtype=tf.int32).numpy()
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [18]:
a = tf.constant(4)
a

<tf.Tensor: id=60, shape=(), dtype=int32, numpy=4>

In [19]:
tf2x.to_float(a)

<tf.Tensor: id=61, shape=(), dtype=float32, numpy=4.0>

<div class="alert alert-block alert-warning" style="margin-top: 20px">
 <h3>Shape Manipulation</h3>
</div>

In [20]:
# It is possible to change the shape of a matrix
# This is easily done using the 'tf.reshape' attribute

a = tf.ones(12).numpy()
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [21]:
a.reshape(3,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [22]:
a.reshape(3,2,2)

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [23]:
# Another way of reshaping a matrix is by using the 'tf.expand_dims()' attribute
# It adds another dimension to a tensor of size 1

a = tf.eye(4)
a

<tf.Tensor: id=68, shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [24]:
b = tf2x.expand_dims(a,0)
b

<tf.Tensor: id=70, shape=(1, 4, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)>

In [25]:
# To get the shape of a tensor, you can call the 'get_shape()' function

b.get_shape()

TensorShape([1, 4, 4])

In [26]:
# The last method which we will be considering is the 'tf.squeeze()'
# This removes all dimensions of size 1 from the matrix

c = tf.squeeze(b)
c

<tf.Tensor: id=71, shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#                           NEXT == Broadcasting in TensorFlow